export const mockData = [
	{
		deletedDate: null,
		id: 91,
		registrationNumber: "SK 01 D 4016",
		type: "Truck",
		make: "TATA",
		model: "TIPPER",
		chassisNumber: null,
		fuelDataSource: "Digital LLS",
		immobilizer: "No Immobilizer",
		tankCapacity: null,
		llsCount: 1,
		odometerReading: null,
		installationDate: "2020-02-02T00:00:00.000Z",
		trialEndDate: null,
		note: "Jeewan",
		status: "Online",
		speedLimit: 0,
		driver: null,
	},
	{
		deletedDate: null,
		id: 499,
		registrationNumber: "SK 01 D 3859",
		type: "Truck",
		make: null,
		model: null,
		chassisNumber: null,
		fuelDataSource: "Digital LLS",
		immobilizer: "No Immobilizer",
		tankCapacity: null,
		llsCount: 2,
		odometerReading: null,
		installationDate: "2021-01-17T00:00:00.000Z",
		trialEndDate: null,
		note: null,
		status: "Online",
		speedLimit: 0,
		driver: null,
	},
	{
		deletedDate: null,
		id: 500,
		registrationNumber: "SK 01 D 1824",
		type: "Truck",
		make: null,
		model: null,
		chassisNumber: null,
		fuelDataSource: "Digital LLS",
		immobilizer: "No Immobilizer",
		tankCapacity: null,
		llsCount: 1,
		odometerReading: null,
		installationDate: "2020-01-17T00:00:00.000Z",
		trialEndDate: null,
		note: "Suspended on Customer Request",
		status: "Suspended",
		speedLimit: 0,
		driver: null,
	},
	{
		deletedDate: null,
		id: 885,
		registrationNumber: "SK 01 D 1759",
		type: "Truck",
		make: null,
		model: null,
		chassisNumber: null,
		fuelDataSource: "Digital LLS",
		immobilizer: "No Immobilizer",
		tankCapacity: null,
		llsCount: 1,
		odometerReading: null,
		installationDate: "2020-01-17T00:00:00.000Z",
		trialEndDate: null,
		note: null,
		status: "Online",
		speedLimit: 0,
		driver: {
			deletedDate: null,
			id: 103,
			name: "Jeewan  Kumar",
			type: "Default",
			phone: "9832376943",
			phoneVerified: true,
			isEnabledSMS: false,
			email: "jeewan.thapa9@gmail.com",
			emailVerified: true,
			isEnabledEmail: false,
			isLoginEnabled: true,
			isEnabledPush: true,
		},
	},
	{
		deletedDate: null,
		id: 886,
		registrationNumber: "SK 01 D 3858",
		type: "Truck",
		make: null,
		model: null,
		chassisNumber: null,
		fuelDataSource: "Digital LLS",
		immobilizer: "No Immobilizer",
		tankCapacity: null,
		llsCount: 2,
		odometerReading: null,
		installationDate: "2020-01-17T00:00:00.000Z",
		trialEndDate: null,
		note: null,
		status: "Online",
		speedLimit: 0,
		driver: null,
	},
	{
		deletedDate: null,
		id: 1317,
		registrationNumber: "AATEST",
		type: "Truck",
		make: null,
		model: null,
		chassisNumber: null,
		fuelDataSource: "No Fuel",
		immobilizer: "No Immobilizer",
		tankCapacity: null,
		llsCount: null,
		odometerReading: null,
		installationDate: "2022-11-09T00:00:00.000Z",
		trialEndDate: "2022-11-10T09:35:01.000Z",
		note: null,
		status: "Online",
		speedLimit: 0,
		driver: null,
	},
	{
		deletedDate: null,
		id: 885,
		registrationNumber: "SK 01 D 1759",
		type: "Truck",
		make: null,
		model: null,
		chassisNumber: null,
		fuelDataSource: "Digital LLS",
		immobilizer: "No Immobilizer",
		tankCapacity: null,
		llsCount: 1,
		odometerReading: null,
		installationDate: "2020-01-17T00:00:00.000Z",
		trialEndDate: null,
		note: null,
		status: "Online",
		speedLimit: 0,
		driver: {
			deletedDate: null,
			id: 103,
			name: "Jeewan  Kumar",
			type: "Default",
			phone: "9832376943",
			phoneVerified: true,
			isEnabledSMS: false,
			email: "jeewan.thapa9@gmail.com",
			emailVerified: true,
			isEnabledEmail: false,
			isLoginEnabled: true,
			isEnabledPush: true,
		},
	},
];

export const liveVehicles = [
	{
		deletedDate: null,
		id: 117,
		registrationNumber: "KA 05 AH 9754",
		type: "Truck",
		make: "TATA",
		model: "TIPPER",
		chassisNumber: null,
		fuelDataSource: "Digital LLS",
		immobilizer: "No Immobilizer",
		tankCapacity: null,
		llsCount: 1,
		odometerReading: null,
		installationDate: "2020-02-02T00:00:00.000Z",
		trialEndDate: null,
		note: "Jeewan",
		status: "Online",
		speedLimit: 0,
		driver: null,
	},
	{
		deletedDate: null,
		id: 118,
		registrationNumber: "KA 05 MM 7108",
		type: "Truck",
		make: "TATA",
		model: "TIPPER",
		chassisNumber: null,
		fuelDataSource: "Digital LLS",
		immobilizer: "No Immobilizer",
		tankCapacity: null,
		llsCount: 1,
		odometerReading: null,
		installationDate: "2020-02-02T00:00:00.000Z",
		trialEndDate: null,
		note: "Jeewan",
		status: "Online",
		speedLimit: 0,
		driver: null,
	},
	{
		deletedDate: null,
		id: 182,
		registrationNumber: "KA 35 P 2198",
		type: "Truck",
		make: "TATA",
		model: "TIPPER",
		chassisNumber: null,
		fuelDataSource: "Digital LLS",
		immobilizer: "No Immobilizer",
		tankCapacity: null,
		llsCount: 1,
		odometerReading: null,
		installationDate: "2020-02-02T00:00:00.000Z",
		trialEndDate: null,
		note: "Jeewan",
		status: "Online",
		speedLimit: 0,
		driver: null,
	},
	{
		deletedDate: null,
		id: 183,
		registrationNumber: "KA 05 AG 5145",
		type: "Truck",
		make: "TATA",
		model: "TIPPER",
		chassisNumber: null,
		fuelDataSource: "Digital LLS",
		immobilizer: "No Immobilizer",
		tankCapacity: null,
		llsCount: 1,
		odometerReading: null,
		installationDate: "2020-02-02T00:00:00.000Z",
		trialEndDate: null,
		note: "Jeewan",
		status: "Online",
		speedLimit: 0,
		driver: null,
	},
	{
		deletedDate: null,
		id: 184,
		registrationNumber: "KA 05 AF 2144",
		type: "Truck",
		make: "TATA",
		model: "TIPPER",
		chassisNumber: null,
		fuelDataSource: "Digital LLS",
		immobilizer: "No Immobilizer",
		tankCapacity: null,
		llsCount: 1,
		odometerReading: null,
		installationDate: "2020-02-02T00:00:00.000Z",
		trialEndDate: null,
		note: "Jeewan",
		status: "Online",
		speedLimit: 0,
		driver: null,
	},
	{
		deletedDate: null,
		id: 265,
		registrationNumber: "WB 73 F 5857",
		type: "Truck",
		make: "TATA",
		model: "TIPPER",
		chassisNumber: null,
		fuelDataSource: "Digital LLS",
		immobilizer: "No Immobilizer",
		tankCapacity: null,
		llsCount: 1,
		odometerReading: null,
		installationDate: "2020-02-02T00:00:00.000Z",
		trialEndDate: null,
		note: "Jeewan",
		status: "Online",
		speedLimit: 0,
		driver: null,
	},
];
